name: "lint protobuf"
on: pull_request

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1

      - name: Install buf
        uses: wizhi/setup-buf@v1
        with:
          version: 0.36.0

      - name: Buf lint
        run: make lint
